### ISSUE TITLE
Cloud CV setup on Local machine

### ISSUE THREAD

**Issue by maheshprabhu** [batra-mlp-lab/CloudCV#46]
Hello,
I was able to successfully install and run all the modules in docker.
Now when i am trying to run Classification task I am getting this error 

Traceback (most recent call last): File "./app/classify_views.py", line 99, in form_valid self.object = form.save() File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 453, in save self.instance.save() File "./app/models.py", line 133, in save super(Classify, self).save(*args, **kwargs) File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 796, in save force_update=force_update, update_fields=update_fields) File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 824, in save_base updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields) File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 908, in _save_table result = self._do_insert(cls._base_manager, using, fields, update_pk, raw) File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 947, in _do_insert using=using, raw=raw) File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1045, in _insert return query.get_compiler(using=using).execute_sql(return_id) File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql cursor.execute(sql, params) File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute return super(CursorDebugWrapper, self).execute(sql, params) File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute return self.cursor.execute(sql, params) File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__ six.reraise(dj_exc_type, dj_exc_value, traceback) File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute return self.cursor.execute(sql, params) File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 337, in execute return Database.Cursor.execute(self, query, params) OperationalError: no such table: app_classify

Am i missing something here. Can someone help please?

**Comment by deshraj** [comment]
It looks like the database migrations didn't run successfully. Can you try the following command: 
`docker exec -it cloudcv_django /bin/bash` 
`python manage.py migrate`

Let me know if this works. 
Also, can you post the result of this command `docker ps` here.

**Comment by maheshprabhu** [comment]
python manage.py migrate --run-syncdb did the trick.. thanks..

**Comment by deshraj** [comment]
Great. :+1:
