### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by b1zantine** [batra-mlp-lab/CloudCV#54]
I built the code using the given instructions but used `conda` environment.
I get `Internal Server Error` when loading the site.

Node server log:
```
[STREAMING] Now streaming realtime logs for [all] processes
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /home/user/chat.js in fork_mode (1 instance)
[PM2] Done.
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬──────────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ watching │
├──────────┼────┼──────┼─────┼────────┼─────────┼────────┼─────┼──────────┼──────────┤
│ chat │ 0 │ fork │ 21 │ online │ 0 │ 0s │ 25% │ 5.7 MB │ disabled │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴──────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2 | 2017-03-05 09:22:32: Time : Sun Mar 05 2017 09:22:32 GMT+0000 (UTC)
PM2 | 2017-03-05 09:22:32: PM2 version : 2.4.2
PM2 | 2017-03-05 09:22:32: Node.js version : 0.12.5
PM2 | 2017-03-05 09:22:32: Current arch : x64
PM2 | 2017-03-05 09:22:32: PM2 home : /root/.pm2
PM2 | 2017-03-05 09:22:32: PM2 PID file : /root/.pm2/pm2.pid
PM2 | 2017-03-05 09:22:32: RPC socket file : /root/.pm2/rpc.sock
PM2 | 2017-03-05 09:22:32: BUS socket file : /root/.pm2/pub.sock
PM2 | 2017-03-05 09:22:32: Application log path : /root/.pm2/logs
PM2 | 2017-03-05 09:22:32: Process dump file : /root/.pm2/dump.pm2
PM2 | 2017-03-05 09:22:32: Concurrent actions : 1
PM2 | 2017-03-05 09:22:32: SIGTERM timeout : 1600
PM2 | 2017-03-05 09:22:32: ===============================================================================
PM2 | 2017-03-05 09:22:32: Starting execution sequence in -fork mode- for app name:chat id:0
PM2 | 2017-03-05 09:22:32: App name:chat id:0 online

/root/.pm2/logs/chat-error-0.log last 15 lines:
0|chat | Error: Redis connection to redis:6379 failed - connect ECONNREFUSED
0|chat | at RedisClient.on_error (/node_modules/redis/index.js:196:24)
0|chat | at Socket.<anonymous> (/node_modules/redis/index.js:106:14)
0|chat | at Socket.emit (events.js:107:17)
0|chat | at net.js:459:14
0|chat | at process._tickDomainCallback [as _tickCallback] (node.js:381:11)

/root/.pm2/logs/chat-out-0.log last 15 lines:
0|chat | info: socket.io started
0|chat | info: socket.io started
0|chat | info: socket.io started
0|chat | info: socket.io started
0|chat | info: socket.io started
0|chat | info: socket.io started
0|chat | info: socket.io started
0|chat | info: socket.io started
0|chat | info: socket.io started
0|chat | info: socket.io started
0|chat | info: socket.io started
0|chat | info: socket.io started
```
Redis server log:
```
1:M 05 Mar 09:22:18.857 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 05 Mar 09:22:18.858 # Server started, Redis version 3.2.8
1:M 05 Mar 09:22:18.858 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 05 Mar 09:22:18.858 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 05 Mar 09:22:18.858 * DB loaded from disk: 0.000 seconds
1:M 05 Mar 09:22:18.858 * The server is now ready to accept connections on port 6379
```

Django server logs:
```
[uWSGI] getting YAML configuration from .travis.yml
*** Starting uWSGI 2.0.13.1 (64bit) on [Sun Mar 5 09:33:03 2017] ***
compiled with version: 4.8.4 on 05 March 2017 06:21:02
os: Linux-3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016
nodename: 130927e3cc85
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /CloudCV_Server
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 524288
your memory page size is 4096 bytes
detected max file descriptor number: 524288
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
Python version: 2.7.6 (default, Oct 26 2016, 20:33:43) [GCC 4.8.4]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1a3fa80
The -s/--socket option is missing and stdin is not a socket.
Sun Mar 5 09:33:03 2017 - [emperor] curse the uwsgi instance .travis.yml (pid: 69)
Sun Mar 5 09:33:06 2017 - [emperor] removed uwsgi instance .travis.yml
```

RabbitMQ logs:
```
=INFO REPORT==== 5-Mar-2017::09:22:27 ===
accepting AMQP connection <0.391.0> (172.17.0.7:51137 -> 172.17.0.3:5672)
```

Nginx had nothing to display.

**Comment by deshraj** [comment]
Hi @SudarAbisheck, this repository is deprecated and we will soon start working on the revamped version. Please see our other projects at http://gsoc.cloudcv.org
